--- @class LuaObjectComponentText:LuaObjectComponent 
--- @field text string 
--- @field font string 
--- @field fontSize number 
--- @field color string 
--- @field outlineColor string 
--- @field outlineWidth number 
--- @field backgroundColor string 
--- @field bold boolean 
--- @field italics boolean 
--- @field xoffset number 
--- @field yoffset number 
LuaObjectComponentText = {}
