--- @class LuaSheetDropdown:Panel 
--- @field options any 
--- @field index any 
--- @field value any The current value the panel represents, if any. This is used for panels that represent controls that allow you to edit a value, such as a checkbox, a dropdown, a color picker, or similar.
--- @field optionChosen any 
--- @field idChosen any 
--- @field allowCustom any 
--- @field dropdownHeight any 
--- @field textOverride any 
--- @field hasSearch any 
LuaSheetDropdown = {}
